name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Make tarball
        run: |
          release_version=$(cat package.json | jq -r '.version')
          echo "RELEASE_VERSION=$release_version" >> $GITHUB_ENV
          cp -R github datasource/.github
          cp -R github component/.github
          cp -R github automation/.github
          tar -C datasource -czf ./datasource.tar.gz ./
          tar -C component -czf ./component.tar.gz ./
          tar -C automation -czf ./automation.tar.gz ./
      - name: Perform Github Release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ env.RELEASE_VERSION }}
          tag_name: v${{ env.RELEASE_VERSION }}
          generate_release_notes: true
          files: |
            datasource.tar.gz
            component.tar.gz
            automation.tar.gz

